<a href="https://colab.research.google.com/github/arturgmrs/imd_tec_002/blob/master/aula_3_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# Pacote Pandas-Python

Adaptado: 
Disciplina: Análise da Aprendizagem (ITE 0021) 

---
Prof.s Isabel Nunes e Luiz Affonso Guedes

PPGTI - UFRN
2019-2


## Pacote Pandas - Parte I

Pandas é construído sobre o Pacote Numpy. Porém, direntemente dos arrays de NumPy, variáveis manipuladas pelo Pandas podem ser de tipos diversos (não homogêneos). Assim, uma determinada variável pode contém elementos de diversos tipos. DataFrame e Series são exemplos de dados complexo de Pandas. 

DataFrames são dados "retangulares", usualmente utilizados para representar informação em formato de planilha, por exemplo. Assim, as colunas devem ter as mesmas dimensões e cada coluna contém elementos de um mesmo tipo de dado.

Series são objetos tipo array uni-dimensional contendo um array de dados (equivalente ao array uni-dimensional NumPy) e um array de labels do array de dados (denominados de index da Serie). Na sua forma mais simples, Series podem conter apenas os arrays de dados. Neste caso, os indexes segue o padrão dos arrays NumPy (índices de zero a n-1).

Pandas implementa uma série de operações sobre dados para usuários familiarizados com banco de dados e planilhas.




Convensão de notação:
- from pandas import Series, DataFrame
- import pandas as pd

In [1]:
# Exemplo: Importanto Pandas

from pandas import Series, DataFrame
import pandas as pd

Series Pandas podem ser vistas como o equivalente ao tipo básico dictionaries. Porém, assim como operações em arrays NumPy são mais eficientes que em Listas, operar em Series é bem mais eficiente que operarar sobre variáveis do tipo Dictonarie. 

In [2]:
# Exemplo: População de alguns estados dos Estados Unidos - Definido como dicionário

pop_dict = {'California': 38332521,
'Texas': 26448193,
'New York': 19651127,
'Florida': 19552860,
'Illinois': 12882135}

In [3]:
# Exemplo: Área de alguns estados dos Estados Unidos
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
'Florida': 170312, 'Illinois': 149995}

In [4]:
dict.values(pop_dict)

dict_values([38332521, 26448193, 19651127, 19552860, 12882135])

In [5]:
dict.keys(pop_dict)

dict_keys(['California', 'Texas', 'New York', 'Florida', 'Illinois'])

In [6]:
#Exercícios: 
#           - Transforme a variável dicionario 'area_dict' em uma Serie-Pandas
#           - Transforme a variável dicionario 'pop_dict' em uma Serie-Pandas        
#           - Obtenha os estados com mais de 20 milhões de habitantes.
#           - Obtenha o número de habitantes da California
#           - Obtenha o estado com mais habitantes
#           - Obtenha o estado com menos habitantes
#           - Obtenha a lista dos estados com área entre 400.000 e 500.000 
#           - A densidade (número de habitantes por área) desses estados



In [7]:
# Transformar dicionário area_dict em Serie-Pandas

area_serie = Series(area_dict)


In [8]:
# Obtendo os valores de uma Serie
area_serie.values

array([423967, 695662, 141297, 170312, 149995])

In [9]:
# Obtendo os indexs das séries
area_serie.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [10]:
# Transformar dicionário pop_dict em Serie-Pandas

pop_serie = Series(pop_dict)

In [ ]:
# Obtendo a situação das áreas dos estados
area_serie>400000

In [11]:
# Obtendo apenas os estados com áreas acima de 400000
area_serie[area_serie>400000]

California    423967
Texas         695662
dtype: int64

In [12]:
# Obtenha os estados com mais de 20 milhões de habitantes.


In [13]:
# Obtenha o número de habitantes da California


In [14]:
# Obtenha o estado com mais habitantes

In [15]:
# Obtenha o estado com menos habitantes


In [16]:
# Obtenha a lista dos estados com área entre 400.000 e 500.000 


In [17]:
# A densidade (número de habitantes por área) desses estados


Os Indexers: loc, iloc
- indicação de índice específico. --> dado[3]
- indicação de intervalo de índices. --> dado[1:3]. Segue o padrão de Lista.
- métodos .loc(), .iloc()

In [18]:
# Exemplo de indicação de índice em Pandas

data = pd.Series(['a', 'b', 'c', 'd'], index=[1,3, 5, 7])
#data = pd.Series(['a', 'b', 'c', 'd'])
data

1    a
3    b
5    c
7    d
dtype: object

In [19]:
# Exemplo de indicação específica de índice em Pandas
data[1]
#data[0]

'a'

In [ ]:
# Exemplo de indicação de intervalo de índice em Pandas
data[1:3]
#data[0:2]

In [21]:
# Exemplo de indicação de índice em Pandas usando o método .loc()
print(data.loc[1])
print()
print(data.loc[1:3])

a

1    a
3    b
dtype: object


In [22]:
# Exemplo de indicação de índice em Pandas usando o método .iloc()
print(data.iloc[1])
print()
print(data.iloc[1:3])

b

3    b
5    c
dtype: object


### Objeto do tipo DataFrame em Pandas

Se uma Serie-Pandas é um análogo de um array NumPy unidimensional com índices explícitos e flexíveis, então um DataFrame é um análogo de array NumPy bidimensional com índices de linha e de colunas flexíveis.

Assim, DataFrame Pandas equivale a uma Matriz com índices explícitos, porém, diferentemenete dos arrays NumPy, os elementos podem ser de tipos diferentes.

DataFrames podem ser vistos como uma sequência de objetos Series-Pandas alinhados por índices.

In [23]:
# Exemplo - Transformação de dict em Serie-Pandas
populacao = pd.Series(pop_dict)
populacao

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [24]:
# Exemplo - Transformação de dict em Serie-Pandas
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [25]:
# Exemplo - Criação de um DataFrame Pandas

estados = pd.DataFrame({'população': populacao,'área': area})
estados

população    área
California   38332521  423967
Texas        26448193  695662
New York     19651127  141297
Florida      19552860  170312
Illinois     12882135  149995

In [26]:
type(estados)

pandas.core.frame.DataFrame

In [27]:
estados.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [28]:
estados.columns

Index(['população', 'área'], dtype='object')

Da mesma forma, também podemos pensar em um DataFrame como uma especialização de um dicionário. Onde um dicionário mapeia uma chave para um valor, um DataFrame mapeia um nome de coluna para uma série de dados de coluna. Por exemplo, pedir o atributo 'área' retorna o objeto Series que contém as áreas que vimos anteriormente:

In [29]:
estados['área']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: área, dtype: int64

In [30]:
# Cálculo da densidade populacional



DataFrame Pandas podem ser criados de diversas formas.
- A partir de objetos Series
- A partir de Listas de Dicionários
- A partir de Dicionários de objetos Series
- A partir de arrays NumPy bidimensionais
- A partir de array NumPy estruturado

In [31]:
# Exemplo: Criação de DataFrame Pandas a partir de objetos Series
pd.DataFrame(populacao, columns=['população'])

população
California   38332521
Texas        26448193
New York     19651127
Florida      19552860
Illinois     12882135

In [32]:
# Exemplo: Criação de DataFrame Pandas a partir de Lista de Dicionário
# Data Missing (Dados perdidos) 

pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

#### Tratando Data Missing em DataFrame
De forma similar a Series, podemos tratar data missing em DataFrame
- técnicas de eliminação
    - df.dropna(parametros)
- técnicas de preenchimento
    - df.fillna(parametros)

In [70]:
# Exemplo: Eliminando data missing em DataFrames
# Eliminar as linhas com NaN
# Eliminar as colunas com NaN
# Eliminar as linhas e colunas com NaN

dataF = DataFrame([[1., 6.5, 3.], [1., None, None], [None, None, None], [None, 6.5, 3.]])
dataF

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [71]:
dataF.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [72]:
dataF.dropna()

0    1    2
0  1.0  6.5  3.0

In [73]:
dataF.dropna(axis='columns')

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

In [74]:
dataF.dropna(how='all', axis='columns')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [75]:
# Exemplo: Preenchimento de data missing em DataFrames
import numpy as np

df = DataFrame(np.random.randn(7, 3))
df

0         1         2
0 -0.127147  0.876575  0.362173
1  0.915473 -0.918148 -0.025869
2  0.896293  1.607821  0.475268
3 -0.722520 -1.386778  1.591524
4  1.844420  0.742082  0.940455
5 -1.551469  0.269473 -0.019679
6  0.501554  1.607274 -1.014959

In [76]:
df.iloc[:4, 1] = None; df.iloc[:2, 2] = None
df

0         1         2
0 -0.127147       NaN       NaN
1  0.915473       NaN       NaN
2  0.896293       NaN  0.475268
3 -0.722520       NaN  1.591524
4  1.844420  0.742082  0.940455
5 -1.551469  0.269473 -0.019679
6  0.501554  1.607274 -1.014959

In [77]:
# Exemplo: Preenchimento de data missing em DataFrames
#          com valor ZERO

df.fillna(0)

0         1         2
0 -0.127147  0.000000  0.000000
1  0.915473  0.000000  0.000000
2  0.896293  0.000000  0.475268
3 -0.722520  0.000000  1.591524
4  1.844420  0.742082  0.940455
5 -1.551469  0.269473 -0.019679
6  0.501554  1.607274 -1.014959

In [78]:
df.iloc[3:4,0:1] = None
df

0         1         2
0 -0.127147       NaN       NaN
1  0.915473       NaN       NaN
2  0.896293       NaN  0.475268
3       NaN       NaN  1.591524
4  1.844420  0.742082  0.940455
5 -1.551469  0.269473 -0.019679
6  0.501554  1.607274 -1.014959

In [79]:
# Exemplo: Preenchimento de data missing em DataFrames
df.fillna(method='ffill')

0         1         2
0 -0.127147       NaN       NaN
1  0.915473       NaN       NaN
2  0.896293       NaN  0.475268
3  0.896293       NaN  1.591524
4  1.844420  0.742082  0.940455
5 -1.551469  0.269473 -0.019679
6  0.501554  1.607274 -1.014959

In [80]:
# Exemplo: Preenchimento de data missing em DataFrames
# Chamando .fillna() com um tipo 'dict', 
# pode-se usar um valor diferente de preenchimento para cada coluna

df.fillna({1: 0.5, 2: -1})

0         1         2
0 -0.127147  0.500000 -1.000000
1  0.915473  0.500000 -1.000000
2  0.896293  0.500000  0.475268
3       NaN  0.500000  1.591524
4  1.844420  0.742082  0.940455
5 -1.551469  0.269473 -0.019679
6  0.501554  1.607274 -1.014959

In [81]:
# Exemplo: Criação de DataFrame Pandas 
#          a partir Dicionários de objetos Series

pd.DataFrame({'população1': populacao,'área1': area})


população1   área1
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

A seguir, são apresentados alguns exemplos de como acessar DataFrames e elementos de DataFrames

In [82]:
estados

população    área   densidade
California   38332521  423967   90.413926
Texas        26448193  695662   38.018740
New York     19651127  141297  139.076746
Florida      19552860  170312  114.806121
Illinois     12882135  149995   85.883763

In [83]:
estados['área']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: área, dtype: int64

In [84]:
estados[['área']]

área
California  423967
Texas       695662
New York    141297
Florida     170312
Illinois    149995

In [85]:
estados[['área','população']]

área  população
California  423967   38332521
Texas       695662   26448193
New York    141297   19651127
Florida     170312   19552860
Illinois    149995   12882135

In [86]:
estados[['população','área', 'área']]

população    área    área
California   38332521  423967  423967
Texas        26448193  695662  695662
New York     19651127  141297  141297
Florida      19552860  170312  170312
Illinois     12882135  149995  149995

In [87]:
estados[['população','área', 'área']][0:3].área

área    área
California  423967  423967
Texas       695662  695662
New York    141297  141297

In [88]:
estados.área

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: área, dtype: int64

Incluir e modificar colunas no DataFrame Pandas
- uma das formas, pode ser usando uma sintaxe similar à sintaxe de dicionários com objetos Series Pandas.


In [89]:
# Exemplo - Inclusão de uma nova coluna no DataFrame Pandas

estados['densidade'] = estados['população'] / estados['área']
estados

população    área   densidade
California   38332521  423967   90.413926
Texas        26448193  695662   38.018740
New York     19651127  141297  139.076746
Florida      19552860  170312  114.806121
Illinois     12882135  149995   85.883763

Como DataFrames podem ser arrays bidimensionais, podemos utilizar operações a esses. 

In [90]:
# Exemplo - Como inverter a representação do DataFrame Pandas
estados.T

California         Texas      New York       Florida      Illinois
população  3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
área       4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
densidade  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [91]:
# Exemplo - Obtendo índicers de DataFrames Pandas
estados.values

array([[3.83325210e+07, 4.23967000e+05, 9.04139261e+01],
       [2.64481930e+07, 6.95662000e+05, 3.80187404e+01],
       [1.96511270e+07, 1.41297000e+05, 1.39076746e+02],
       [1.95528600e+07, 1.70312000e+05, 1.14806121e+02],
       [1.28821350e+07, 1.49995000e+05, 8.58837628e+01]])

In [92]:
# Exemplo - Obtendo índices de DataFrames Pandas
estados.values[0]

array([3.83325210e+07, 4.23967000e+05, 9.04139261e+01])

In [93]:
# Exemplo - Obtendo índices de DataFrames Pandas
estados.values[:][0]

array([3.83325210e+07, 4.23967000e+05, 9.04139261e+01])

In [94]:
estados[estados.densidade > 100]

população    área   densidade
New York   19651127  141297  139.076746
Florida    19552860  170312  114.806121

In [95]:
estados.densidade > 100

California    False
Texas         False
New York       True
Florida        True
Illinois      False
Name: densidade, dtype: bool

In [96]:
estados[estados.densidade > 100].densidade

New York    139.076746
Florida     114.806121
Name: densidade, dtype: float64

In [97]:
estados[estados.densidade > 100][['população', 'densidade']]

população   densidade
New York   19651127  139.076746
Florida    19552860  114.806121

In [98]:
# Exercício: Liste o atributo 'densidade'
#           dos estados da Florida e Illinois 

In [99]:
# Exemplo de listagem de sub-DataFrame em Pandas
# O método .iloc() pemite acesso por numeração - localicação

estados.iloc[:3, :2]

#estados[:3,:2]

população    área
California   38332521  423967
Texas        26448193  695662
New York     19651127  141297

In [100]:
# Exemplo de listagem de sub-DataFrame em Pandas
# O método .loc() permite acesso por labels

estados.loc[:'Illinois', :'população']

população
California   38332521
Texas        26448193
New York     19651127
Florida      19552860
Illinois     12882135

In [101]:
estados

população    área   densidade
California   38332521  423967   90.413926
Texas        26448193  695662   38.018740
New York     19651127  141297  139.076746
Florida      19552860  170312  114.806121
Illinois     12882135  149995   85.883763

In [102]:
# Exemplo de listagem de sub-DataFrame em Pandas
# Uso do estilo NumPy para acessar sub Arrays
# Formato:
# dataFrame.loc[LINHAS, COLUNAS]

estados.loc[estados.densidade > 100, ['população', 'densidade']]

população   densidade
New York   19651127  139.076746
Florida    19552860  114.806121

In [103]:
# Exercício: 
# Obenha apenas os Estados com população acima de 20 milhões.
# Exiba as colunas 'população'e 'densidade'



Métodos:
    - pd.head(x)  --> lista as x primeiras linhas do DataFrame
    - pd.tail(x)  --> lista as x últimas linhas do DataFrame
    - pd.info()   --> resume o conteúdo do DataFrame

In [104]:
# Exemplo de uso do método pd.head()
estados.head(2)
#estados.head()

população    área  densidade
California   38332521  423967  90.413926
Texas        26448193  695662  38.018740

In [105]:
# Exemplo de uso do método pd.tail()
estados.tail(2)
#estados.tail()

população    área   densidade
Florida    19552860  170312  114.806121
Illinois   12882135  149995   85.883763

In [106]:
# Exemplo de uso do método pd.info()
estados.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, California to Illinois
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   população  5 non-null      int64  
 1   área       5 non-null      int64  
 2   densidade  5 non-null      float64
dtypes: float64(1), int64(2)
memory usage: 320.0+ bytes


Como se pode alterar os valores de elementos de DataFrames?


### Pandas foi desenvolvido sobre o NumPy e manteve a compatibilidade das operações NumPy.
- dados Pandas (Series, DataFrame) aceitam as operações NumPy

In [107]:
# Exemplo de operação NumPy sobre dados Pandas
# Definindo o objeto ser - Tipo Series Pandas
import pandas as pd
import numpy as np

rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0, 10, 4))
ser

0    6
1    3
2    7
3    4
dtype: int64

In [108]:
# Exemplo de operação NumPy sobre dados Pandas
# Operação exponencial sobre um objeto Series Pandas

np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [109]:
# Exemplo de operação NumPy sobre dados Pandas
# Definindo o objeto df - Tipo DataFrame Pandas

df = pd.DataFrame(rng.randint(0, 10, (3, 4)),
columns=['A', 'B', 'C', 'D'])
df

A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [110]:
# Exemplo de operação NumPy sobre dados Pandas
# Operação seno sobre um objeto DataFrame Pandas

np.sin(df * np.pi / 4)

A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16